#############################################################################
# Makefile for building: SMAH_RPI_UI
# Generated by qmake (3.1) (Qt 5.12.5)
# Project:  SMAH_RPI_UI.pro
# Template: app
# Command: /usr/lib64/qt5/bin/qmake -o Makefile SMAH_RPI_UI.pro -spec linux-g++ CONFIG+=qml_debug CONFIG+=debug
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_MESSAGELOGCONTEXT -DQT_QML_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_NETWORK_LIB -DQT_XML_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/home/lenny/PROJECTS/SMAH_RPI_UI/src/../_lib -isystem /usr/local/include/openzwave -isystem /usr/local/include -isystem /usr/include/qt5 -isystem /usr/include/qt5/QtWidgets -isystem /usr/include/qt5/QtGui -isystem /usr/include/qt5/QtNetwork -isystem /usr/include/qt5/QtXml -isystem /usr/include/qt5/QtCore -I. -isystem /usr/include/libdrm -I. -I/usr/lib64/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib64/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib64/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib64/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = SMAH_RPI_UI1.0.0
DISTDIR = /home/lenny/PROJECTS/SMAH_RPI_UI/src/.tmp/SMAH_RPI_UI1.0.0
LINK          = g++
LFLAGS        = 
LIBS          = $(SUBLIBS) -L/home/lenny/PROJECTS/SMAH_RPI_UI/src/../../../../../usr/local/lib/arm/ -L/home/lenny/PROJECTS/SMAH_RPI_UI/src/../../../../../usr/local/lib64/ -lopenzwave -lpigpio /usr/lib64/libQt5Widgets.so /usr/lib64/libQt5Gui.so /usr/lib64/libQt5Network.so /usr/lib64/libQt5Xml.so /usr/lib64/libQt5Core.so /usr/lib64/libGL.so -lpthread   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		mainwindow.cpp \
		rpidevice.cpp \
		widgets/w_colorpreview.cpp \
		widgets/w_hsvwheel.cpp \
		widgets/w_lightcontrolcontainer.cpp \
		widgets/w_powercontrol.cpp \
		widgets/w_presetchooser.cpp \
		widgets/w_scheduledactions.cpp \
		widgets/w_systemsettings.cpp \
		widgets/w_topheader.cpp \
		widgets/w_zonechooser.cpp \
		widgets/w_zonecontainer.cpp \
		widgets/w_zoneenvironment.cpp \
		widgets/w_zoneoverview.cpp \
		logger.cpp \
		preset.cpp \
		datagramhandler.cpp \
		widgets/w_zone_lights.cpp \
		light.cpp \
		tcpsocket.cpp \
		presettask.cpp \
		zone.cpp \
		pca9685.cpp \
		i2c/i2c.cpp \
		commandrouter.cpp \
		zwavemanager.cpp \
		sunriseset.cpp \
		widgets/w_screensaver.cpp \
		sensor.cpp \
		widgets/w_zonefunctionsbasewidget.cpp \
		ui_mainwindow.cpp \
		rsslisting.cpp \
		tcpconnectionfactory.cpp \
		w_weatherwidget.cpp moc_mainwindow.cpp \
		moc_rpidevice.cpp \
		moc_w_colorpreview.cpp \
		moc_w_hsvpalette.cpp \
		moc_w_lightcontrolcontainer.cpp \
		moc_w_powercontrol.cpp \
		moc_w_presetchooser.cpp \
		moc_w_scheduledactions.cpp \
		moc_w_systemsettings.cpp \
		moc_w_topheader.cpp \
		moc_w_zonechooser.cpp \
		moc_w_zonecontainer.cpp \
		moc_w_zoneenvironment.cpp \
		moc_w_zoneoverview.cpp \
		moc_datagramhandler.cpp \
		moc_w_zone_lights.cpp \
		moc_light.cpp \
		moc_presettask.cpp \
		moc_tcpsocket.cpp \
		moc_w_screensaver.cpp \
		moc_eventfilter.cpp \
		moc_sensor.cpp \
		moc_w_zonefunctionsbasewidget.cpp \
		moc_ui_mainwindow.cpp \
		moc_rsslisting.cpp \
		moc_tcpconnectionfactory.cpp \
		moc_w_weatherwidget.cpp
OBJECTS       = main.o \
		mainwindow.o \
		rpidevice.o \
		w_colorpreview.o \
		w_hsvwheel.o \
		w_lightcontrolcontainer.o \
		w_powercontrol.o \
		w_presetchooser.o \
		w_scheduledactions.o \
		w_systemsettings.o \
		w_topheader.o \
		w_zonechooser.o \
		w_zonecontainer.o \
		w_zoneenvironment.o \
		w_zoneoverview.o \
		logger.o \
		preset.o \
		datagramhandler.o \
		w_zone_lights.o \
		light.o \
		tcpsocket.o \
		presettask.o \
		zone.o \
		pca9685.o \
		i2c.o \
		commandrouter.o \
		zwavemanager.o \
		sunriseset.o \
		w_screensaver.o \
		sensor.o \
		w_zonefunctionsbasewidget.o \
		ui_mainwindow.o \
		rsslisting.o \
		tcpconnectionfactory.o \
		w_weatherwidget.o \
		moc_mainwindow.o \
		moc_rpidevice.o \
		moc_w_colorpreview.o \
		moc_w_hsvpalette.o \
		moc_w_lightcontrolcontainer.o \
		moc_w_powercontrol.o \
		moc_w_presetchooser.o \
		moc_w_scheduledactions.o \
		moc_w_systemsettings.o \
		moc_w_topheader.o \
		moc_w_zonechooser.o \
		moc_w_zonecontainer.o \
		moc_w_zoneenvironment.o \
		moc_w_zoneoverview.o \
		moc_datagramhandler.o \
		moc_w_zone_lights.o \
		moc_light.o \
		moc_presettask.o \
		moc_tcpsocket.o \
		moc_w_screensaver.o \
		moc_eventfilter.o \
		moc_sensor.o \
		moc_w_zonefunctionsbasewidget.o \
		moc_ui_mainwindow.o \
		moc_rsslisting.o \
		moc_tcpconnectionfactory.o \
		moc_w_weatherwidget.o
DIST          = ../../../../../usr/local/include/openzwave/aes/aes.txt \
		/usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		SMAH_RPI_UI.pro mainwindow.h \
		rpidevice.h \
		widgets/w_colorpreview.h \
		widgets/w_hsvpalette.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_powercontrol.h \
		widgets/w_presetchooser.h \
		widgets/w_scheduledactions.h \
		widgets/w_systemsettings.h \
		widgets/w_topheader.h \
		widgets/w_zonechooser.h \
		widgets/w_zonecontainer.h \
		widgets/w_zoneenvironment.h \
		widgets/w_zoneoverview.h \
		build_number.h \
		logger.h \
		preset.h \
		datagramhandler.h \
		widgets/w_zone_lights.h \
		light.h \
		gpio_defs.h \
		zone.h \
		pca9685.h \
		i2c/i2c.h \
		build_number.h \
		logger.h \
		pca9685.h \
		preset.h \
		presettask.h \
		tcpsocket.h \
		zone.h \
		zwavemanager.h \
		sunriseset.h \
		widgets/w_screensaver.h \
		eventfilter.h \
		sensor.h \
		commandrouter.h \
		widgets/qengravedlabel.h \
		widgets/w_zonefunctionsbasewidget.h \
		ui_mainwindow.h \
		rsslisting.h \
		tcpconnectionfactory.h \
		w_weatherwidget.h main.cpp \
		mainwindow.cpp \
		rpidevice.cpp \
		widgets/w_colorpreview.cpp \
		widgets/w_hsvwheel.cpp \
		widgets/w_lightcontrolcontainer.cpp \
		widgets/w_powercontrol.cpp \
		widgets/w_presetchooser.cpp \
		widgets/w_scheduledactions.cpp \
		widgets/w_systemsettings.cpp \
		widgets/w_topheader.cpp \
		widgets/w_zonechooser.cpp \
		widgets/w_zonecontainer.cpp \
		widgets/w_zoneenvironment.cpp \
		widgets/w_zoneoverview.cpp \
		logger.cpp \
		preset.cpp \
		datagramhandler.cpp \
		widgets/w_zone_lights.cpp \
		light.cpp \
		tcpsocket.cpp \
		presettask.cpp \
		zone.cpp \
		pca9685.cpp \
		i2c/i2c.cpp \
		commandrouter.cpp \
		zwavemanager.cpp \
		sunriseset.cpp \
		widgets/w_screensaver.cpp \
		sensor.cpp \
		widgets/w_zonefunctionsbasewidget.cpp \
		ui_mainwindow.cpp \
		rsslisting.cpp \
		tcpconnectionfactory.cpp \
		w_weatherwidget.cpp
QMAKE_TARGET  = SMAH_RPI_UI
DESTDIR       = 
TARGET        = SMAH_RPI_UI


first: all
####### Build rules

SMAH_RPI_UI: build_nr ui_ui_mainwindow.h ui_weatherwidget.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: SMAH_RPI_UI.pro /usr/lib64/qt5/mkspecs/linux-g++/qmake.conf /usr/lib64/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib64/qt5/mkspecs/common/unix.conf \
		/usr/lib64/qt5/mkspecs/common/linux.conf \
		/usr/lib64/qt5/mkspecs/common/sanitize.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib64/qt5/mkspecs/common/g++-base.conf \
		/usr/lib64/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib64/qt5/mkspecs/qconfig.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri \
		/usr/lib64/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib64/qt5/mkspecs/features/qt_config.prf \
		/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib64/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib64/qt5/mkspecs/features/toolchain.prf \
		/usr/lib64/qt5/mkspecs/features/default_pre.prf \
		/usr/lib64/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib64/qt5/mkspecs/features/default_post.prf \
		/usr/lib64/qt5/mkspecs/features/qml_debug.prf \
		/usr/lib64/qt5/mkspecs/features/warn_on.prf \
		/usr/lib64/qt5/mkspecs/features/qt.prf \
		/usr/lib64/qt5/mkspecs/features/resources.prf \
		/usr/lib64/qt5/mkspecs/features/moc.prf \
		/usr/lib64/qt5/mkspecs/features/unix/opengl.prf \
		/usr/lib64/qt5/mkspecs/features/uic.prf \
		/usr/lib64/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib64/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib64/qt5/mkspecs/features/file_copies.prf \
		/usr/lib64/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib64/qt5/mkspecs/features/exceptions.prf \
		/usr/lib64/qt5/mkspecs/features/yacc.prf \
		/usr/lib64/qt5/mkspecs/features/lex.prf \
		SMAH_RPI_UI.pro
	$(QMAKE) -o Makefile SMAH_RPI_UI.pro -spec linux-g++ CONFIG+=qml_debug CONFIG+=debug
/usr/lib64/qt5/mkspecs/features/spec_pre.prf:
/usr/lib64/qt5/mkspecs/common/unix.conf:
/usr/lib64/qt5/mkspecs/common/linux.conf:
/usr/lib64/qt5/mkspecs/common/sanitize.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base.conf:
/usr/lib64/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib64/qt5/mkspecs/common/g++-base.conf:
/usr/lib64/qt5/mkspecs/common/g++-unix.conf:
/usr/lib64/qt5/mkspecs/qconfig.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KAuth.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCodecs.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KCoreAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KItemViews.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KJobWidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_KWidgetsAddons.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib64/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib64/qt5/mkspecs/modules/qt_Solid.pri:
/usr/lib64/qt5/mkspecs/features/qt_functions.prf:
/usr/lib64/qt5/mkspecs/features/qt_config.prf:
/usr/lib64/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib64/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib64/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib64/qt5/mkspecs/features/toolchain.prf:
/usr/lib64/qt5/mkspecs/features/default_pre.prf:
/usr/lib64/qt5/mkspecs/features/resolve_config.prf:
/usr/lib64/qt5/mkspecs/features/default_post.prf:
/usr/lib64/qt5/mkspecs/features/qml_debug.prf:
/usr/lib64/qt5/mkspecs/features/warn_on.prf:
/usr/lib64/qt5/mkspecs/features/qt.prf:
/usr/lib64/qt5/mkspecs/features/resources.prf:
/usr/lib64/qt5/mkspecs/features/moc.prf:
/usr/lib64/qt5/mkspecs/features/unix/opengl.prf:
/usr/lib64/qt5/mkspecs/features/uic.prf:
/usr/lib64/qt5/mkspecs/features/unix/thread.prf:
/usr/lib64/qt5/mkspecs/features/qmake_use.prf:
/usr/lib64/qt5/mkspecs/features/file_copies.prf:
/usr/lib64/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib64/qt5/mkspecs/features/exceptions.prf:
/usr/lib64/qt5/mkspecs/features/yacc.prf:
/usr/lib64/qt5/mkspecs/features/lex.prf:
SMAH_RPI_UI.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile SMAH_RPI_UI.pro -spec linux-g++ CONFIG+=qml_debug CONFIG+=debug

qmake_all: FORCE


all: Makefile SMAH_RPI_UI

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib64/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents mainwindow.h rpidevice.h widgets/w_colorpreview.h widgets/w_hsvpalette.h widgets/w_lightcontrolcontainer.h widgets/w_powercontrol.h widgets/w_presetchooser.h widgets/w_scheduledactions.h widgets/w_systemsettings.h widgets/w_topheader.h widgets/w_zonechooser.h widgets/w_zonecontainer.h widgets/w_zoneenvironment.h widgets/w_zoneoverview.h build_number.h logger.h preset.h datagramhandler.h widgets/w_zone_lights.h light.h gpio_defs.h zone.h pca9685.h i2c/i2c.h build_number.h logger.h pca9685.h preset.h presettask.h tcpsocket.h zone.h zwavemanager.h sunriseset.h widgets/w_screensaver.h eventfilter.h sensor.h commandrouter.h widgets/qengravedlabel.h widgets/w_zonefunctionsbasewidget.h ui_mainwindow.h rsslisting.h tcpconnectionfactory.h w_weatherwidget.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp mainwindow.cpp rpidevice.cpp widgets/w_colorpreview.cpp widgets/w_hsvwheel.cpp widgets/w_lightcontrolcontainer.cpp widgets/w_powercontrol.cpp widgets/w_presetchooser.cpp widgets/w_scheduledactions.cpp widgets/w_systemsettings.cpp widgets/w_topheader.cpp widgets/w_zonechooser.cpp widgets/w_zonecontainer.cpp widgets/w_zoneenvironment.cpp widgets/w_zoneoverview.cpp logger.cpp preset.cpp datagramhandler.cpp widgets/w_zone_lights.cpp light.cpp tcpsocket.cpp presettask.cpp zone.cpp pca9685.cpp i2c/i2c.cpp commandrouter.cpp zwavemanager.cpp sunriseset.cpp widgets/w_screensaver.cpp sensor.cpp widgets/w_zonefunctionsbasewidget.cpp ui_mainwindow.cpp rsslisting.cpp tcpconnectionfactory.cpp w_weatherwidget.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ui_mainwindow.ui weatherwidget.ui $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

build_nr: FORCE
	../build_number.sh

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib64/qt5/mkspecs/features/data/dummy.cpp
	g++ -pipe -g -Wall -W -dM -E -o moc_predefs.h /usr/lib64/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_mainwindow.cpp moc_rpidevice.cpp moc_w_colorpreview.cpp moc_w_hsvpalette.cpp moc_w_lightcontrolcontainer.cpp moc_w_powercontrol.cpp moc_w_presetchooser.cpp moc_w_scheduledactions.cpp moc_w_systemsettings.cpp moc_w_topheader.cpp moc_w_zonechooser.cpp moc_w_zonecontainer.cpp moc_w_zoneenvironment.cpp moc_w_zoneoverview.cpp moc_datagramhandler.cpp moc_w_zone_lights.cpp moc_light.cpp moc_presettask.cpp moc_tcpsocket.cpp moc_w_screensaver.cpp moc_eventfilter.cpp moc_sensor.cpp moc_w_zonefunctionsbasewidget.cpp moc_ui_mainwindow.cpp moc_rsslisting.cpp moc_tcpconnectionfactory.cpp moc_w_weatherwidget.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_rpidevice.cpp moc_w_colorpreview.cpp moc_w_hsvpalette.cpp moc_w_lightcontrolcontainer.cpp moc_w_powercontrol.cpp moc_w_presetchooser.cpp moc_w_scheduledactions.cpp moc_w_systemsettings.cpp moc_w_topheader.cpp moc_w_zonechooser.cpp moc_w_zonecontainer.cpp moc_w_zoneenvironment.cpp moc_w_zoneoverview.cpp moc_datagramhandler.cpp moc_w_zone_lights.cpp moc_light.cpp moc_presettask.cpp moc_tcpsocket.cpp moc_w_screensaver.cpp moc_eventfilter.cpp moc_sensor.cpp moc_w_zonefunctionsbasewidget.cpp moc_ui_mainwindow.cpp moc_rsslisting.cpp moc_tcpconnectionfactory.cpp moc_w_weatherwidget.cpp
moc_mainwindow.cpp: mainwindow.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		widgets/w_topheader.h \
		widgets/w_systemsettings.h \
		widgets/w_screensaver.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include mainwindow.h -o moc_mainwindow.cpp

moc_rpidevice.cpp: rpidevice.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include rpidevice.h -o moc_rpidevice.cpp

moc_w_colorpreview.cpp: widgets/w_colorpreview.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_colorpreview.h -o moc_w_colorpreview.cpp

moc_w_hsvpalette.cpp: widgets/w_hsvpalette.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_hsvpalette.h -o moc_w_hsvpalette.cpp

moc_w_lightcontrolcontainer.cpp: widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		zone.h \
		rpidevice.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_lightcontrolcontainer.h -o moc_w_lightcontrolcontainer.cpp

moc_w_powercontrol.cpp: widgets/w_powercontrol.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_powercontrol.h -o moc_w_powercontrol.cpp

moc_w_presetchooser.cpp: widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_presetchooser.h -o moc_w_presetchooser.cpp

moc_w_scheduledactions.cpp: widgets/w_scheduledactions.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_scheduledactions.h -o moc_w_scheduledactions.cpp

moc_w_systemsettings.cpp: widgets/w_systemsettings.h \
		rpidevice.h \
		widgets/qengravedlabel.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_systemsettings.h -o moc_w_systemsettings.cpp

moc_w_topheader.cpp: widgets/w_topheader.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_topheader.h -o moc_w_topheader.cpp

moc_w_zonechooser.cpp: widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_zonechooser.h -o moc_w_zonechooser.cpp

moc_w_zonecontainer.cpp: widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_zonecontainer.h -o moc_w_zonecontainer.cpp

moc_w_zoneenvironment.cpp: widgets/w_zoneenvironment.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_zoneenvironment.h -o moc_w_zoneenvironment.cpp

moc_w_zoneoverview.cpp: widgets/w_zoneoverview.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_zoneoverview.h -o moc_w_zoneoverview.cpp

moc_datagramhandler.cpp: datagramhandler.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		rpidevice.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include datagramhandler.h -o moc_datagramhandler.cpp

moc_w_zone_lights.cpp: widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		zone.h \
		rpidevice.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_zone_lights.h -o moc_w_zone_lights.cpp

moc_light.cpp: light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include light.h -o moc_light.cpp

moc_presettask.cpp: presettask.h \
		preset.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include presettask.h -o moc_presettask.cpp

moc_tcpsocket.cpp: tcpsocket.h \
		rpidevice.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include tcpsocket.h -o moc_tcpsocket.cpp

moc_w_screensaver.cpp: widgets/w_screensaver.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_screensaver.h -o moc_w_screensaver.cpp

moc_eventfilter.cpp: eventfilter.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include eventfilter.h -o moc_eventfilter.cpp

moc_sensor.cpp: sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		rpidevice.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include sensor.h -o moc_sensor.cpp

moc_w_zonefunctionsbasewidget.cpp: widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include widgets/w_zonefunctionsbasewidget.h -o moc_w_zonefunctionsbasewidget.cpp

moc_ui_mainwindow.cpp: ui_mainwindow.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include ui_mainwindow.h -o moc_ui_mainwindow.cpp

moc_rsslisting.cpp: rsslisting.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include rsslisting.h -o moc_rsslisting.cpp

moc_tcpconnectionfactory.cpp: tcpconnectionfactory.h \
		tcpsocket.h \
		rpidevice.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include tcpconnectionfactory.h -o moc_tcpconnectionfactory.cpp

moc_w_weatherwidget.cpp: w_weatherwidget.h \
		moc_predefs.h \
		/usr/lib64/qt5/bin/moc
	/usr/lib64/qt5/bin/moc $(DEFINES) --include /home/lenny/PROJECTS/SMAH_RPI_UI/src/moc_predefs.h -I/usr/lib64/qt5/mkspecs/linux-g++ -I/home/lenny/PROJECTS/SMAH_RPI_UI/src -I/home/lenny/PROJECTS/SMAH_RPI_UI/_lib -I/usr/local/include/openzwave -I/usr/local/include -I/usr/include/qt5 -I/usr/include/qt5/QtWidgets -I/usr/include/qt5/QtGui -I/usr/include/qt5/QtNetwork -I/usr/include/qt5/QtXml -I/usr/include/qt5/QtCore -I/usr/include/c++/8 -I/usr/include/c++/8/x86_64-redhat-linux -I/usr/include/c++/8/backward -I/usr/lib/gcc/x86_64-redhat-linux/8/include -I/usr/local/include -I/usr/include w_weatherwidget.h -o moc_w_weatherwidget.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_ui_mainwindow.h ui_weatherwidget.h
compiler_uic_clean:
	-$(DEL_FILE) ui_ui_mainwindow.h ui_weatherwidget.h
ui_ui_mainwindow.h: ui_mainwindow.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic ui_mainwindow.ui -o ui_ui_mainwindow.h

ui_weatherwidget.h: weatherwidget.ui \
		/usr/lib64/qt5/bin/uic
	/usr/lib64/qt5/bin/uic weatherwidget.ui -o ui_weatherwidget.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

main.o: main.cpp zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		mainwindow.h \
		widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		widgets/w_topheader.h \
		widgets/w_systemsettings.h \
		widgets/w_screensaver.h \
		logger.h \
		datagramhandler.h \
		gpio_defs.h \
		pca9685.h \
		i2c/i2c.h \
		eventfilter.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		widgets/w_topheader.h \
		widgets/w_systemsettings.h \
		widgets/w_screensaver.h \
		ui_mainwindow.h \
		w_weatherwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

rpidevice.o: rpidevice.cpp rpidevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rpidevice.o rpidevice.cpp

w_colorpreview.o: widgets/w_colorpreview.cpp widgets/w_colorpreview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_colorpreview.o widgets/w_colorpreview.cpp

w_hsvwheel.o: widgets/w_hsvwheel.cpp widgets/w_hsvpalette.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_hsvwheel.o widgets/w_hsvwheel.cpp

w_lightcontrolcontainer.o: widgets/w_lightcontrolcontainer.cpp widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		zone.h \
		rpidevice.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_hsvpalette.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		mainwindow.h \
		widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_topheader.h \
		widgets/w_systemsettings.h \
		widgets/w_screensaver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_lightcontrolcontainer.o widgets/w_lightcontrolcontainer.cpp

w_powercontrol.o: widgets/w_powercontrol.cpp widgets/w_powercontrol.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_powercontrol.o widgets/w_powercontrol.cpp

w_presetchooser.o: widgets/w_presetchooser.cpp widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		mainwindow.h \
		widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		widgets/w_topheader.h \
		widgets/w_systemsettings.h \
		widgets/w_screensaver.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_presetchooser.o widgets/w_presetchooser.cpp

w_scheduledactions.o: widgets/w_scheduledactions.cpp widgets/w_scheduledactions.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_scheduledactions.o widgets/w_scheduledactions.cpp

w_systemsettings.o: widgets/w_systemsettings.cpp widgets/w_systemsettings.h \
		rpidevice.h \
		widgets/qengravedlabel.h \
		build_number.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		sensor.h \
		zwavemanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_systemsettings.o widgets/w_systemsettings.cpp

w_topheader.o: widgets/w_topheader.cpp widgets/w_topheader.h \
		mainwindow.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		widgets/w_systemsettings.h \
		widgets/w_screensaver.h \
		sunriseset.h \
		rsslisting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_topheader.o widgets/w_topheader.cpp

w_zonechooser.o: widgets/w_zonechooser.cpp widgets/w_zonechooser.h \
		widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		widgets/w_zoneenvironment.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_zonechooser.o widgets/w_zonechooser.cpp

w_zonecontainer.o: widgets/w_zonecontainer.cpp widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_zonecontainer.o widgets/w_zonecontainer.cpp

w_zoneenvironment.o: widgets/w_zoneenvironment.cpp widgets/w_zoneenvironment.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_zoneenvironment.o widgets/w_zoneenvironment.cpp

w_zoneoverview.o: widgets/w_zoneoverview.cpp widgets/w_zoneoverview.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_zoneoverview.o widgets/w_zoneoverview.cpp

logger.o: logger.cpp logger.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o logger.o logger.cpp

preset.o: preset.cpp preset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o preset.o preset.cpp

datagramhandler.o: datagramhandler.cpp datagramhandler.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		rpidevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datagramhandler.o datagramhandler.cpp

w_zone_lights.o: widgets/w_zone_lights.cpp light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		zone.h \
		rpidevice.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_presetchooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_zone_lights.o widgets/w_zone_lights.cpp

light.o: light.cpp light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		gpio_defs.h \
		commandrouter.h \
		zone.h \
		rpidevice.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		pca9685.h \
		i2c/i2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o light.o light.cpp

tcpsocket.o: tcpsocket.cpp tcpsocket.h \
		rpidevice.h \
		zone.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		build_number.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpsocket.o tcpsocket.cpp

presettask.o: presettask.cpp presettask.h \
		preset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o presettask.o presettask.cpp

zone.o: zone.cpp zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zone.o zone.cpp

pca9685.o: pca9685.cpp pca9685.h \
		i2c/i2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pca9685.o pca9685.cpp

i2c.o: i2c/i2c.cpp i2c/i2c.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o i2c.o i2c/i2c.cpp

commandrouter.o: commandrouter.cpp commandrouter.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o commandrouter.o commandrouter.cpp

zwavemanager.o: zwavemanager.cpp zwavemanager.h \
		commandrouter.h \
		zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zwavemanager.o zwavemanager.cpp

sunriseset.o: sunriseset.cpp sunriseset.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sunriseset.o sunriseset.cpp

w_screensaver.o: widgets/w_screensaver.cpp zone.h \
		rpidevice.h \
		light.h \
		preset.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/w_screensaver.h \
		widgets/w_zoneenvironment.h \
		widgets/qengravedlabel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_screensaver.o widgets/w_screensaver.cpp

sensor.o: sensor.cpp sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		rpidevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sensor.o sensor.cpp

w_zonefunctionsbasewidget.o: widgets/w_zonefunctionsbasewidget.cpp widgets/w_zonefunctionsbasewidget.h \
		widgets/w_zonecontainer.h \
		widgets/w_presetchooser.h \
		preset.h \
		zone.h \
		rpidevice.h \
		light.h \
		presettask.h \
		zwavemanager.h \
		sensor.h \
		tcpconnectionfactory.h \
		tcpsocket.h \
		widgets/qengravedlabel.h \
		widgets/w_powercontrol.h \
		widgets/w_zoneoverview.h \
		widgets/w_zone_lights.h \
		widgets/w_lightcontrolcontainer.h \
		widgets/w_colorpreview.h \
		widgets/w_zonechooser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_zonefunctionsbasewidget.o widgets/w_zonefunctionsbasewidget.cpp

ui_mainwindow.o: ui_mainwindow.cpp ui_mainwindow.h \
		ui_ui_mainwindow.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ui_mainwindow.o ui_mainwindow.cpp

rsslisting.o: rsslisting.cpp rsslisting.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o rsslisting.o rsslisting.cpp

tcpconnectionfactory.o: tcpconnectionfactory.cpp tcpconnectionfactory.h \
		tcpsocket.h \
		rpidevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tcpconnectionfactory.o tcpconnectionfactory.cpp

w_weatherwidget.o: w_weatherwidget.cpp w_weatherwidget.h \
		ui_weatherwidget.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o w_weatherwidget.o w_weatherwidget.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_rpidevice.o: moc_rpidevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rpidevice.o moc_rpidevice.cpp

moc_w_colorpreview.o: moc_w_colorpreview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_colorpreview.o moc_w_colorpreview.cpp

moc_w_hsvpalette.o: moc_w_hsvpalette.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_hsvpalette.o moc_w_hsvpalette.cpp

moc_w_lightcontrolcontainer.o: moc_w_lightcontrolcontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_lightcontrolcontainer.o moc_w_lightcontrolcontainer.cpp

moc_w_powercontrol.o: moc_w_powercontrol.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_powercontrol.o moc_w_powercontrol.cpp

moc_w_presetchooser.o: moc_w_presetchooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_presetchooser.o moc_w_presetchooser.cpp

moc_w_scheduledactions.o: moc_w_scheduledactions.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_scheduledactions.o moc_w_scheduledactions.cpp

moc_w_systemsettings.o: moc_w_systemsettings.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_systemsettings.o moc_w_systemsettings.cpp

moc_w_topheader.o: moc_w_topheader.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_topheader.o moc_w_topheader.cpp

moc_w_zonechooser.o: moc_w_zonechooser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_zonechooser.o moc_w_zonechooser.cpp

moc_w_zonecontainer.o: moc_w_zonecontainer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_zonecontainer.o moc_w_zonecontainer.cpp

moc_w_zoneenvironment.o: moc_w_zoneenvironment.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_zoneenvironment.o moc_w_zoneenvironment.cpp

moc_w_zoneoverview.o: moc_w_zoneoverview.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_zoneoverview.o moc_w_zoneoverview.cpp

moc_datagramhandler.o: moc_datagramhandler.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datagramhandler.o moc_datagramhandler.cpp

moc_w_zone_lights.o: moc_w_zone_lights.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_zone_lights.o moc_w_zone_lights.cpp

moc_light.o: moc_light.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_light.o moc_light.cpp

moc_presettask.o: moc_presettask.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_presettask.o moc_presettask.cpp

moc_tcpsocket.o: moc_tcpsocket.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpsocket.o moc_tcpsocket.cpp

moc_w_screensaver.o: moc_w_screensaver.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_screensaver.o moc_w_screensaver.cpp

moc_eventfilter.o: moc_eventfilter.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventfilter.o moc_eventfilter.cpp

moc_sensor.o: moc_sensor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sensor.o moc_sensor.cpp

moc_w_zonefunctionsbasewidget.o: moc_w_zonefunctionsbasewidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_zonefunctionsbasewidget.o moc_w_zonefunctionsbasewidget.cpp

moc_ui_mainwindow.o: moc_ui_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_ui_mainwindow.o moc_ui_mainwindow.cpp

moc_rsslisting.o: moc_rsslisting.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_rsslisting.o moc_rsslisting.cpp

moc_tcpconnectionfactory.o: moc_tcpconnectionfactory.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_tcpconnectionfactory.o moc_tcpconnectionfactory.cpp

moc_w_weatherwidget.o: moc_w_weatherwidget.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_w_weatherwidget.o moc_w_weatherwidget.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

